# Generated by Django 4.2.16 on 2024-12-10 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0002_pet_pet_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="pet_image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="placeholder",
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="pets/",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pet_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
