# Generated by Django 4.2.16 on 2024-12-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_pet_pet_image"),
        ("booking", "0002_alter_booking_pet_alter_booking_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="approved",
            new_name="slotapproved",
        ),
        migrations.AlterField(
            model_name="booking",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="dashboard.pet",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.slot",
            ),
        ),
    ]
