# Generated by Django 4.2.16 on 2024-12-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_booking_options_remove_booking_booking_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="booking_time",
            field=models.CharField(
                choices=[
                    ("10:00", "10:00"),
                    ("12:00", "12:00"),
                    ("14:00", "14:00"),
                    ("16:00", "16:00"),
                ]
            ),
        ),
    ]
